MusicApp/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:index, :show, :new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :bands
  resources :albums, only: [:new, :create, :edit, :show, :update, :destroy]
  resources :tracks, only: [:new, :create, :edit, :show, :update, :destroy]
  resources :notes

end

MusicApp/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id             :integer          not null, primary key
#  name           :string           not null
#  band_id        :integer          not null
#  live_recording :boolean          default(FALSE), not null
#  created_at     :datetime
#  updated_at     :datetime
#

class Album < ActiveRecord::Base

has_many :tracks,
class_name: 'Track',
foreign_key: :album_id,
primary_key: :id,
dependent: :destroy

belongs_to :band,
class_name: 'Band',
foreign_key: :band_id,
primary_key: :id


end

MusicApp/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime
#  updated_at :datetime
#

class Band < ActiveRecord::Base

  has_many :albums,
  class_name: 'Album',
  foreign_key: :band_id,
  primary_key: :id,
  dependent: :destroy

end

MusicApp/app/models/note.rb
class Note < ActiveRecord::Base

  validates :body, :track_id, :user_id, presence: true

  belongs_to :track,
  class_name: 'Track',
  foreign_key: :track_id,
  primary_key: :id

  belongs_to :user,
  class_name: 'User',
  foreign_key: :user_id,
  primary_key: :id

end

MusicApp/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  album_id   :integer          not null
#  bonus      :boolean          default(FALSE), not null
#  lyrics     :text
#  created_at :datetime
#  updated_at :datetime
#

class Track < ActiveRecord::Base

  belongs_to :album

  has_many :notes,
  class_name: 'Note',
  foreign_key: :track_id,
  primary_key: :id
end

MusicApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime
#  updated_at      :datetime
#

require 'byebug'

class User < ActiveRecord::Base

  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return user if user && user.is_password?(password)
    nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end



end

MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def new
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to band_url(@album.band.id)
    else
      flash[:errors] = ["Error! No album created!"]
      render :new
    end
  end


  private

    def album_params
      params.require(:album).permit(:name, :band_id, :live_recording)
    end

end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :log_in_user!, :logged_in?, :current_user


  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def log_in_user!
    session[:session_token] = @user.session_token
  end


end

MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  attr_accessor :bands


  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      render :show
    else
      flash[:errors] = ["Error! No band created!"]
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.update(band_params)
    if @band.save
      render :show
    else
      flash[:errors] = ["Error! No band created!"]
      render :edit
    end
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end


end

MusicApp/app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def new
    render :new
  end

  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    if @note.save
      redirect_to track_url(@note.track_id)
    else
      flash[:errors] = ["Error! No error created!"]
      redirect_to track_url(@note.track_id)
    end
  end

  private
  def note_params
    params.require(:note).permit(:track_id, :body)
  end

end

MusicApp/app/controllers/sessions_controller.rb
require 'byebug'

class SessionsController < ApplicationController

  helper_method :log_in_user!, :logged_in?, :current_user

    def new
      render :new
    end

    def create
      @user = User.find_by_credentials(
        user_params[:email],
        user_params[:password]
      )
      if @user
        @user.reset_session_token!
        log_in_user!
        redirect_to user_url(@user)
      else
        flash[:errors] = ["Unable to login!"]
        render :new
      end
    end

    def destroy
        current_user.reset_session_token!
        session[:session_token] = nil
        current_user = nil
        redirect_to new_session_url
    end


    private

    def user_params
      params.require(:user).permit(:email, :password)
    end



end

MusicApp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def new
    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      render :show
    else
      flash[:errors] = ["Error! No track created!"]
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def update
    @track = Track.update(track_params)
    if @track.save
      render :show
    else
      flash[:errors] = ["Error! Nothing updated!"]
      render :new
    end
  end


  private

  def track_params
    params.require(:track).permit(:name, :album_id, :bonus, :lyrics)
  end



end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  helper_method :log_in_user!, :logged_in?

  def index
    @users = User.all
    render:index
  end

  def new
    render :new
  end

  def create
    # Add functionality to auto log in user when created
    @user = User.new(user_params)
    if @user.save
      render text: "placeholder for index page"
    else
      flash[:errors] = ["Error! No user created!"]
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end


  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MusicApp/app/views/albums/new.html.erb
<h3>Create Album in the Database:</h3>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
<% end %>

<form action="<%=albums_url%>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">

  <label for="name" name="name">Album Name:</label>
  <input type="text" name="album[name]"  id="name">
  <br><br>

  <label for="band_id" id="band">Band</label>
  <select name="album[band_id]" id="band">
    <% Band.all.each do |band| %>
      <option value="<%=band.id %>"><%=band.name %></option>
    <% end %>
  </select>
  <br><br>

  Style:
  <input type="radio" name="album[live_recording]" id="live" value="<%=true %>">
  <label for="live">Live Recording</label>

  <input type="radio" name="album[live_recording]" id="studio" value="<%=false %>">
  <label for="studio">Studio Recording</label>
  <br><br>

  <input type="submit" value="Submit">
</form>

MusicApp/app/views/albums/show.html.erb
<h3><%= @album.name %></h3>

<ul>
  <% @album.tracks.each do |track| %>
    <li><%= link_to "#{track.name}", track_url(track) %></li>
  <% end %>
</ul>


<%= link_to "Add New Track", new_track_url %> ||
<%= link_to "Back to Artist", band_url(@album.band.id) %> ||
<%= link_to "Back to Band Directory", bands_url %>

MusicApp/app/views/bands/edit.html.erb
<h3>Edit a Band in the Database:</h3>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
<% end %>

<form action="<%=band_url%>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">

  <label for="name" name="name">Band Name:</label>
  <input type="text" name="band[name]" id="name" value="<%=@band.name %>">

  <input type="submit" value="Submit">
</form>

MusicApp/app/views/bands/index.html.erb
<h3>App Academy Artists</h3>

<ul>
  <% @bands.each do |band| %>
    <li><%= link_to "#{band.name}", band_url(band) %></li>
  <% end %>
</ul>

<%= link_to "Add Band to Database", new_band_url %>

MusicApp/app/views/bands/new.html.erb
<h3>Create a Band in the Database:</h3>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
<% end %>

<form action="<%=bands_url%>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">

  <label for="name" name="name">Band Name:</label>
  <input type="text" name="band[name]"  id="name">

  <input type="submit" value="Submit">
</form>

MusicApp/app/views/bands/show.html.erb
<h3><%= @band.name %></h3>

<ul>
  <% @band.albums.each do |album| %>
    <li><i><%= link_to "#{album.name}", album_url(album) %></i></li>
  <% end %>
</ul>


<%= link_to "Add New Album", new_album_url %> ||
<%= link_to "Edit Band", edit_band_url %> ||
<%= link_to "Back to List of Artists", bands_url %>

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <!-- <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %> -->
  <!-- <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> -->
  <%= csrf_meta_tags %>
</head>
<font face="Arial">
<h1><font color="red">a/A</font> || AppAcademy Records || <img src="http://a2.mzstatic.com/us/r30/Purple62/v4/c1/49/5a/c1495af1-04c1-f034-f21c-23bdf99cab5c/icon128-2x.png" height="35" width="35"></h1>
<hr>
<header>
    <% if logged_in? %>

      <%= current_user.email %> is currently logged in ...
      <form action="<%= session_url %>" method="POST">
        <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Sign Out">
      </form>

    <% else %>

      <form action="<%=new_session_url %>" method="GET">
        <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">
        <input type ="submit" value="Log in">
      </form>

    <% end %>

</header>

<body>

<%= yield %>

</body>
</font>
</html>

MusicApp/app/views/notes/_note.html.erb
<h4>Comments</h4>

<% @track.notes.each do |note| %>
  <%= note.body %>
  <%= note.user.email %>
<% end %>

MusicApp/app/views/tracks/edit.html.erb
<h3>Edit Track to Database:</h3>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
<% end %>

<form action="<%=track_url%>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">

  <label for="name" name="name">Track Name:</label>
  <input type="text" name="track[name]" value="<%=@track.name %>" id="name">
  <br><br>

  <label for="album_id" id="album">Album</label>
  <select name="track[album_id]" id="album">
    <% Album.all.each do |album| %>
      <option value="<%=album.id %>"><%=album.name %></option>
    <% end %>
  </select>
  <br><br>

  Style:
  <input type="radio" name="track[bonus]" id="bonus" value="<%=true %>">
  <label for="bonus">Bonus Track</label>

  <input type="radio" name="track[bonus]" id="regular" value="<%=false %>">
  <label for="regular">Regular Track</label>
  <br><br>

  <label for="lyrics">Lyrics:</label>
  <textarea name="track[lyrics]" id="lyrics" cols="50" rows="10"></textarea>
  <br>

  <input type="submit" value="Submit">
</form>

MusicApp/app/views/tracks/new.html.erb
<h3>Add Track to Database:</h3>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
<% end %>

<form action="<%=tracks_url%>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">

  <label for="name" name="name">Track Name:</label>
  <input type="text" name="track[name]"  id="name">
  <br><br>

  <label for="album_id" id="album">Album</label>
  <select name="track[album_id]" id="album">
    <% Album.all.each do |album| %>
      <option value="<%=album.id %>"><%=album.name %></option>
    <% end %>
  </select>
  <br><br>

  Style:
  <input type="radio" name="track[bonus]" id="bonus" value="<%=true %>">
  <label for="bonus">Bonus Track</label>

  <input type="radio" name="track[bonus]" id="regular" value="<%=false %>">
  <label for="regular">Regular Track</label>
  <br><br>

  <input type="submit" value="Submit">
</form>

MusicApp/app/views/tracks/show.html.erb
<h3><%= @track.name %></h3>
<h4>Lyrics</h4>

<%= link_to "Edit Track", edit_track_url %>
<%= link_to "Back to Album", album_url(@track.album.id) %> ||
<%= link_to "Back to Band Directory", bands_url %>


<h3>Comments</h3>
<% @track.notes.each do |note| %>
  <p><%= note.body %>
  <br><font size="2"><%= note.user.email %>
  <br><%= note.created_at %></font></p>
<% end %>


<h3>Add New Comment</h3>

<form action="<%=notes_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">
  <input type="hidden" name="note[track_id]" value="<%= @track.id %>">
  <label for="notes">Comment:</label>
  <textarea name="note[body]" id="notes" cols="50" rows="10"></textarea>
  <br>
  <input type="submit" value="Submit Comment">
</form>

MusicApp/app/views/users/index.html.erb
<h3><u>Directory of Users</u></h3>

<% @users.each do |user| %>
  <p><%=user.email %></p>
<% end %>

MusicApp/app/views/users/show.html.erb
<h3>User Profile</h3>

<b>Email Address:</b> <%= @user.email %>